calls:
  - config: "search_route"
  - config: "search_trip"
  - config: "select"
  - config: "init"
  - config: "confirm"
  - config: "status"
  - config: "on_search_route"
    endpoint: "mapper/ondc"
  - config: "on_search_trip"
    endpoint: "mapper/ondc"
  - config: "on_select"
    endpoint: "mapper/ondc"
  - config: "on_init"
    endpoint: "mapper/ondc"
  - config: "on_confirm"
    endpoint: "mapper/ondc"
  - config: "on_status"
    endpoint: "mapper/ondc"
